Repository LeonardoCalazans/Calculadora-Romana, pull requests merged in 2022-04, with the labels that each got.

#1 [FEATURE] - Alterado botões da calculadora para algarismo romano
  css/calculator.css
  css/style.css
  index.html
  js/index.js
  main.js
Labels: enhancement, wontfix

#2 Feature/nygma02 - Separado os dados do array, utilizado conversor e refatorado para melhores práticas
  index.html
  js/index.js
Labels: enhancement, code review needed ⌚

#7 Leonardo/refactor
  css/reset.css
  css/style.css
  js/modules/convertToRoman.js
Labels: refactor
